import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en' | 'km';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.alumni': '校友目录',
    'nav.events': '活动中心',
    'nav.news': '校友动态',
    'nav.profile': '个人资料',
    'nav.logout': '退出',
    'nav.brandName': '校友网络',

    // Dashboard
    'dashboard.welcome': '欢迎回来！',
    'dashboard.totalAlumni': '注册校友',
    'dashboard.totalEvents': '活动总数',
    'dashboard.myRegistrations': '我的报名',
    'dashboard.totalNews': '动态总数',
    'dashboard.upcomingEvents': '即将举行',
    'dashboard.latestNews': '最新动态',
    'dashboard.viewAll': '查看全部',
    'dashboard.quickActions': '快速操作',
    'dashboard.searchAlumni': '搜索校友',
    'dashboard.browseEvents': '浏览活动',
    'dashboard.viewNews': '查看动态',
    'dashboard.editProfile': '编辑资料',
    'dashboard.noEvents': '暂无即将举行的活动',
    'dashboard.noNews': '暂无动态',

    // Profile
    'profile.title': '个人资料',
    'profile.subtitle': '管理您的个人信息和校友网络档案',
    'profile.edit': '编辑资料',
    'profile.save': '保存',
    'profile.cancel': '取消',
    'profile.name': '姓名',
    'profile.email': '邮箱',
    'profile.phone': '电话',
    'profile.location': '所在地区',
    'profile.company': '公司',
    'profile.position': '职位',
    'profile.graduationYear': '毕业年份',
    'profile.major': '专业',
    'profile.industry': '行业',
    'profile.bio': '个人简介',
    'profile.notSet': '未设置',
    'profile.online': '在线',

    // Alumni Directory
    'alumni.title': '校友目录',
    'alumni.subtitle': '发现和联系优秀的校友们',
    'alumni.found': '共找到',
    'alumni.people': '位校友',
    'alumni.search': '搜索姓名、公司、职位或专业...',
    'alumni.allYears': '所有年份',
    'alumni.allIndustries': '所有行业',
    'alumni.allLocations': '所有地区',
    'alumni.clearFilters': '清除筛选',
    'alumni.message': '私信',
    'alumni.noResults': '没有找到匹配的校友',
    'alumni.tryAdjusting': '尝试调整搜索条件或筛选器',

    // Events
    'events.title': '活动中心',
    'events.subtitle': '参与校友活动，拓展人脉网络',
    'events.create': '创建活动',
    'events.search': '搜索活动...',
    'events.allCategories': '所有类别',
    'events.register': '立即报名',
    'events.people': '人',
    'events.createModal': '创建活动',
    'events.titleLabel': '活动标题',
    'events.description': '活动描述',
    'events.date': '活动日期',
    'events.maxAttendees': '最大人数',
    'events.location': '活动地点',
    'events.category': '活动类别',

    // News
    'news.title': '校友动态',
    'news.subtitle': '了解最新的校友资讯和行业动态',
    'news.publish': '发布动态',
    'news.comments': '评论',
    'news.writeComment': '写下你的评论...',
    'news.noComments': '暂无评论',

    // Common
    'common.loading': '加载中...',
    'common.cancel': '取消',
    'common.confirm': '确定',
    'common.success': '成功',
    'common.error': '错误',
    'common.selectPlaceholder': '请选择',
    'common.anonymous': '匿名',

    // Landing Page
    'landing.universityName': '柬埔寨大学',
    'landing.alumniNetwork': '校友网络',
    'landing.connectAlumni': '连接 1200+ 优秀校友',
    'landing.everyMeeting': '让每一次',
    'landing.encounter': '相遇',
    'landing.fullOf': '都充满',
    'landing.possibility': '可能',
    'landing.subtitle1': '打造专业的校友生态平台，汇聚全球校友资源',
    'landing.subtitle2': '共享职业机会，传承校园精神，创造无限价值',
    'landing.joinNow': '立即加入，探索更多',
    'landing.hasAccount': '已有账号？立即登录',
    'landing.benefit1': '终身免费使用',
    'landing.benefit2': '无广告干扰',
    'landing.benefit3': '7x24小时技术支持',
    'landing.coreFeatures': '核心功能',
    'landing.forAlumni': '为校友打造的',
    'landing.comprehensivePlatform': '全方位平台',
    'landing.featuresDesc': '整合最需要的功能，提供最优质的服务，让校友关系管理变得简单高效',
    'landing.feature1Title': '智能校友目录',
    'landing.feature1Desc': '按届别、专业、地区、行业智能搜索，精准定位校友资源',
    'landing.feature2Title': '活动管理',
    'landing.feature2Desc': '线上线下活动一站式管理，轻松组织校友聚会与交流',
    'landing.feature3Title': '实时互动',
    'landing.feature3Desc': '动态发布、评论点赞，随时分享校友成就与行业洞察',
    'landing.feature4Title': '全球网络',
    'landing.feature4Desc': '连接全球校友，打破地域限制，构建国际化人脉圈',
    'landing.feature5Title': '职业发展',
    'landing.feature5Desc': '职业机会共享，导师指导，助力校友职业成长',
    'landing.feature6Title': '隐私保护',
    'landing.feature6Desc': '企业级安全加密，完善的隐私设置，保护个人信息',
    'landing.dataSpeak': '用数据说话',
    'landing.dataDesc': '每一个数字背后，都是校友们的信任与支持',
    'landing.stat1': '注册校友',
    'landing.stat2': '活跃用户',
    'landing.stat3': '举办活动',
    'landing.stat4': '成功合作',
    'landing.testimonialTitle': '校友心声',
    'landing.testimonialSubtitle': '听听校友们怎么说',
    'landing.testimonial1Name': '张明',
    'landing.testimonial1Title': '2015届校友',
    'landing.testimonial1Company': '腾讯高级产品经理',
    'landing.testimonial1Content': '通过校友网络，我找到了现在的工作机会。平台让我与优秀的校友们保持联系，互相学习成长。',
    'landing.testimonial2Name': '李华',
    'landing.testimonial2Title': '2018届校友',
    'landing.testimonial2Company': '字节跳动技术总监',
    'landing.testimonial2Content': '校友网络是我职业发展的重要助力。在这里不仅找到了导师，还结识了很多志同道合的朋友。',
    'landing.testimonial3Name': 'Sarah Chen',
    'landing.testimonial3Title': '2020届校友',
    'landing.testimonial3Company': '创业公司创始人',
    'landing.testimonial3Content': '作为创业者，校友网络给我提供了宝贵的资源和支持。感谢平台让校友关系更紧密！',
    'landing.ctaTitle': '准备好开启校友之旅了吗？',
    'landing.ctaSubtitle': '加入我们，与优秀的校友们建立联系，共同成长，创造更多可能',
    'landing.ctaButton': '免费注册，立即开始',
    'landing.footerTagline': '连接校友 · 共创未来',
    'landing.footerCopyright': '© 2024 Alumni Network. All rights reserved.',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.alumni': 'Alumni Directory',
    'nav.events': 'Events',
    'nav.news': 'News',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.brandName': 'Alumni Network',

    // Dashboard
    'dashboard.welcome': 'Welcome Back!',
    'dashboard.totalAlumni': 'Total Alumni',
    'dashboard.totalEvents': 'Total Events',
    'dashboard.myRegistrations': 'My Registrations',
    'dashboard.totalNews': 'Total News',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.latestNews': 'Latest News',
    'dashboard.viewAll': 'View All',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.searchAlumni': 'Search Alumni',
    'dashboard.browseEvents': 'Browse Events',
    'dashboard.viewNews': 'View News',
    'dashboard.editProfile': 'Edit Profile',
    'dashboard.noEvents': 'No upcoming events',
    'dashboard.noNews': 'No news available',

    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your personal information and alumni network profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.company': 'Company',
    'profile.position': 'Position',
    'profile.graduationYear': 'Graduation Year',
    'profile.major': 'Major',
    'profile.industry': 'Industry',
    'profile.bio': 'Bio',
    'profile.notSet': 'Not Set',
    'profile.online': 'Online',

    // Alumni Directory
    'alumni.title': 'Alumni Directory',
    'alumni.subtitle': 'Discover and connect with outstanding alumni',
    'alumni.found': 'Found',
    'alumni.people': 'alumni',
    'alumni.search': 'Search name, company, position or major...',
    'alumni.allYears': 'All Years',
    'alumni.allIndustries': 'All Industries',
    'alumni.allLocations': 'All Locations',
    'alumni.clearFilters': 'Clear Filters',
    'alumni.message': 'Message',
    'alumni.noResults': 'No matching alumni found',
    'alumni.tryAdjusting': 'Try adjusting your search criteria or filters',

    // Events
    'events.title': 'Events Center',
    'events.subtitle': 'Join alumni events and expand your network',
    'events.create': 'Create Event',
    'events.search': 'Search events...',
    'events.allCategories': 'All Categories',
    'events.register': 'Register Now',
    'events.people': 'people',
    'events.createModal': 'Create Event',
    'events.titleLabel': 'Event Title',
    'events.description': 'Event Description',
    'events.date': 'Event Date',
    'events.maxAttendees': 'Max Attendees',
    'events.location': 'Event Location',
    'events.category': 'Event Category',

    // News
    'news.title': 'Alumni News',
    'news.subtitle': 'Stay updated with the latest alumni news and industry insights',
    'news.publish': 'Publish News',
    'news.comments': 'Comments',
    'news.writeComment': 'Write your comment...',
    'news.noComments': 'No comments yet',

    // Common
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.selectPlaceholder': 'Please select',
    'common.anonymous': 'Anonymous',

    // Landing Page
    'landing.universityName': 'Cambodia University',
    'landing.alumniNetwork': 'Alumni Network',
    'landing.connectAlumni': 'Connect with 1200+ Outstanding Alumni',
    'landing.everyMeeting': 'Every',
    'landing.encounter': 'Encounter',
    'landing.fullOf': 'Is Full Of',
    'landing.possibility': 'Possibilities',
    'landing.subtitle1': 'Build a professional alumni ecosystem platform, gathering global alumni resources',
    'landing.subtitle2': 'Share career opportunities, inherit campus spirit, create unlimited value',
    'landing.joinNow': 'Join Now, Explore More',
    'landing.hasAccount': 'Already have an account? Login',
    'landing.benefit1': 'Free Forever',
    'landing.benefit2': 'Ad-Free Experience',
    'landing.benefit3': '24/7 Technical Support',
    'landing.coreFeatures': 'Core Features',
    'landing.forAlumni': 'Built for',
    'landing.comprehensivePlatform': 'Alumni',
    'landing.featuresDesc': 'Integrating essential features, providing premium services, making alumni relationship management simple and efficient',
    'landing.feature1Title': 'Smart Alumni Directory',
    'landing.feature1Desc': 'Intelligent search by graduation year, major, region, and industry to precisely locate alumni resources',
    'landing.feature2Title': 'Event Management',
    'landing.feature2Desc': 'One-stop management for online and offline events, easily organize alumni gatherings and exchanges',
    'landing.feature3Title': 'Real-time Interaction',
    'landing.feature3Desc': 'Post updates, comment and like, share alumni achievements and industry insights anytime',
    'landing.feature4Title': 'Global Network',
    'landing.feature4Desc': 'Connect with alumni worldwide, break geographical barriers, build an international network',
    'landing.feature5Title': 'Career Development',
    'landing.feature5Desc': 'Share career opportunities, mentorship guidance, support alumni career growth',
    'landing.feature6Title': 'Privacy Protection',
    'landing.feature6Desc': 'Enterprise-grade security encryption, comprehensive privacy settings, protect personal information',
    'landing.dataSpeak': 'Numbers Speak',
    'landing.dataDesc': 'Behind every number is the trust and support of our alumni',
    'landing.stat1': 'Registered Alumni',
    'landing.stat2': 'Active Users',
    'landing.stat3': 'Events Held',
    'landing.stat4': 'Successful Collaborations',
    'landing.testimonialTitle': 'Alumni Voices',
    'landing.testimonialSubtitle': 'Hear what our alumni say',
    'landing.testimonial1Name': 'Zhang Ming',
    'landing.testimonial1Title': 'Class of 2015',
    'landing.testimonial1Company': 'Senior Product Manager at Tencent',
    'landing.testimonial1Content': 'Through the alumni network, I found my current job opportunity. The platform keeps me connected with outstanding alumni, learning and growing together.',
    'landing.testimonial2Name': 'Li Hua',
    'landing.testimonial2Title': 'Class of 2018',
    'landing.testimonial2Company': 'Technical Director at ByteDance',
    'landing.testimonial2Content': 'The alumni network is a vital force in my career development. I not only found mentors here but also met many like-minded friends.',
    'landing.testimonial3Name': 'Sarah Chen',
    'landing.testimonial3Title': 'Class of 2020',
    'landing.testimonial3Company': 'Startup Founder',
    'landing.testimonial3Content': 'As an entrepreneur, the alumni network provides me with valuable resources and support. Thank you for making alumni relationships closer!',
    'landing.ctaTitle': 'Ready to Start Your Alumni Journey?',
    'landing.ctaSubtitle': 'Join us, connect with outstanding alumni, grow together, and create more possibilities',
    'landing.ctaButton': 'Sign Up Free, Start Now',
    'landing.footerTagline': 'Connecting Alumni · Creating Future',
    'landing.footerCopyright': '© 2024 Alumni Network. All rights reserved.',
  },
  km: {
    // Navigation
    'nav.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
    'nav.alumni': 'បញ្ជីអតីតនិស្សិត',
    'nav.events': 'ព្រឹត្តិការណ៍',
    'nav.news': 'ព័ត៌មាន',
    'nav.profile': 'ប្រវត្តិរូប',
    'nav.logout': 'ចាកចេញ',
    'nav.brandName': 'បណ្តាញអតីតនិស្សិត',

    // Dashboard
    'dashboard.welcome': 'សូមស្វាគមន៍!',
    'dashboard.totalAlumni': 'អតីតនិស្សិតសរុប',
    'dashboard.totalEvents': 'ព្រឹត្តិការណ៍សរុប',
    'dashboard.myRegistrations': 'ការចុះឈ្មោះរបស់ខ្ញុំ',
    'dashboard.totalNews': 'ព័ត៌មានសរុប',
    'dashboard.upcomingEvents': 'ព្រឹត្តិការណ៍នាពេលខាងមុខ',
    'dashboard.latestNews': 'ព័ត៌មានថ្មីៗ',
    'dashboard.viewAll': 'មើលទាំងអស់',
    'dashboard.quickActions': 'សកម្មភាពរហ័ស',
    'dashboard.searchAlumni': 'ស្វែងរកអតីតនិស្សិត',
    'dashboard.browseEvents': 'រកមើលព្រឹត្តិការណ៍',
    'dashboard.viewNews': 'មើលព័ត៌មាន',
    'dashboard.editProfile': 'កែប្រែប្រវត្តិរូប',
    'dashboard.noEvents': 'មិនមានព្រឹត្តិការណ៍នៅឡើយទេ',
    'dashboard.noNews': 'មិនមានព័ត៌មាន',

    // Profile
    'profile.title': 'ប្រវត្តិរូប',
    'profile.subtitle': 'គ្រប់គ្រងព័ត៌មានផ្ទាល់ខ្លួននិងប្រវត្តិរូបបណ្តាញអតីតនិស្សិត',
    'profile.edit': 'កែប្រែប្រវត្តិរូប',
    'profile.save': 'រក្សាទុក',
    'profile.cancel': 'បោះបង់',
    'profile.name': 'ឈ្មោះ',
    'profile.email': 'អ៊ីមែល',
    'profile.phone': 'ទូរស័ព្ទ',
    'profile.location': 'ទីតាំង',
    'profile.company': 'ក្រុមហ៊ុន',
    'profile.position': 'មុខតំណែង',
    'profile.graduationYear': 'ឆ្នាំបញ្ចប់ការសិក្សា',
    'profile.major': 'ជំនាញ',
    'profile.industry': 'ឧស្សាហកម្ម',
    'profile.bio': 'ប្រវត្តិសង្ខេប',
    'profile.notSet': 'មិនទាន់កំណត់',
    'profile.online': 'អនឡាញ',

    // Alumni Directory
    'alumni.title': 'បញ្ជីអតីតនិស្សិត',
    'alumni.subtitle': 'រកឃើញនិងភ្ជាប់ទំនាក់ទំនងជាមួយអតីតនិស្សិតល្អៗ',
    'alumni.found': 'រកឃើញ',
    'alumni.people': 'នាក់',
    'alumni.search': 'ស្វែងរកឈ្មោះ ក្រុមហ៊ុន មុខតំណែង ឬជំនាញ...',
    'alumni.allYears': 'ឆ្នាំទាំងអស់',
    'alumni.allIndustries': 'ឧស្សាហកម្មទាំងអស់',
    'alumni.allLocations': 'ទីតាំងទាំងអស់',
    'alumni.clearFilters': 'សម្អាតតម្រង',
    'alumni.message': 'ផ្ញើសារ',
    'alumni.noResults': 'រកមិនឃើញអតីតនិស្សិតដែលត្រូវគ្នា',
    'alumni.tryAdjusting': 'សូមសាកល្បងកែប្រែលក្ខខណ្ឌស្វែងរក',

    // Events
    'events.title': 'មជ្ឈមណ្ឌលព្រឹត្តិការណ៍',
    'events.subtitle': 'ចូលរួមព្រឹត្តិការណ៍អតីតនិស្សិតនិងពង្រីកបណ្តាញ',
    'events.create': 'បង្កើតព្រឹត្តិការណ៍',
    'events.search': 'ស្វែងរកព្រឹត្តិការណ៍...',
    'events.allCategories': 'ប្រភេទទាំងអស់',
    'events.register': 'ចុះឈ្មោះឥឡូវនេះ',
    'events.people': 'នាក់',
    'events.createModal': 'បង្កើតព្រឹត្តិការណ៍',
    'events.titleLabel': 'ចំណងជើងព្រឹត្តិការណ៍',
    'events.description': 'ការពិពណ៌នា',
    'events.date': 'កាលបរិច្ឆេទ',
    'events.maxAttendees': 'អ្នកចូលរួមអតិបរមា',
    'events.location': 'ទីតាំង',
    'events.category': 'ប្រភេទ',

    // News
    'news.title': 'ព័ត៌មានអតីតនិស្សិត',
    'news.subtitle': 'ទទួលបានព័ត៌មានថ្មីៗពីអតីតនិស្សិតនិងឧស្សាហកម្ម',
    'news.publish': 'បោះពុម្ពផ្សាយ',
    'news.comments': 'មតិយោបល់',
    'news.writeComment': 'សរសេរមតិយោបល់របស់អ្នក...',
    'news.noComments': 'មិនទាន់មានមតិយោបល់',

    // Common
    'common.loading': 'កំពុងផ្ទុក...',
    'common.cancel': 'បោះបង់',
    'common.confirm': 'បញ្ជាក់',
    'common.success': 'ជោគជ័យ',
    'common.error': 'កំហុស',
    'common.selectPlaceholder': 'សូមជ្រើសរើស',
    'common.anonymous': 'អនាមិក',

    // Landing Page
    'landing.universityName': 'សាកលវិទ្យាល័យកម្ពុជា',
    'landing.alumniNetwork': 'បណ្តាញអតីតនិស្សិត',
    'landing.connectAlumni': 'ភ្ជាប់ជាមួយអតីតនិស្សិតល្អៗ 1200+ នាក់',
    'landing.everyMeeting': 'រាល់',
    'landing.encounter': 'ការជួបគ្នា',
    'landing.fullOf': 'គឺពេញដោយ',
    'landing.possibility': 'លទ្ធភាព',
    'landing.subtitle1': 'បង្កើតវេទិកាអតីតនិស្សិតវិជ្ជាជីវៈ ប្រមូលធនធានអតីតនិស្សិតពីទូទាំងពិភពលោក',
    'landing.subtitle2': 'ចែករំលែកឱកាសការងារ បន្តស្មារតីសាលារៀន បង្កើតតម្លៃគ្មានដែនកំណត់',
    'landing.joinNow': 'ចូលរួមឥឡូវនេះ ស្វែងរកបន្ថែម',
    'landing.hasAccount': 'មានគណនីរួចហើយ? ចូលភ្លាម',
    'landing.benefit1': 'ប្រើប្រាស់ដោយឥតគិតថ្លៃអស់មួយជីវិត',
    'landing.benefit2': 'គ្មានការរំខានពីផ្សាយពាណិជ្ជកម្ម',
    'landing.benefit3': 'ការគាំទ្របច្ចេកទេស 24/7',
    'landing.coreFeatures': 'មុខងារស្នូល',
    'landing.forAlumni': 'បង្កើតឡើងសម្រាប់',
    'landing.comprehensivePlatform': 'អតីតនិស្សិត',
    'landing.featuresDesc': 'រួមបញ្ចូលមុខងារចាំបាច់ ផ្តល់សេវាកម្មល្អបំផុត ធ្វើឱ្យការគ្រប់គ្រងទំនាក់ទំនងអតីតនិស្សិតងាយស្រួល',
    'landing.feature1Title': 'បញ្ជីអតីតនិស្សិតឆ្លាតវៃ',
    'landing.feature1Desc': 'ស្វែងរកឆ្លាតវៃតាមឆ្នាំបញ្ចប់ការសិក្សា ជំនាញ តំបន់ ឧស្សាហកម្ម ដើម្បីកំណត់ធនធានអតីតនិស្សិតដោយត្រឹមត្រូវ',
    'landing.feature2Title': 'ការគ្រប់គ្រងព្រឹត្តិការណ៍',
    'landing.feature2Desc': 'ការគ្រប់គ្រងតែមួយចំណុចសម្រាប់ព្រឹត្តិការណ៍លើបណ្តាញនិងក្រៅបណ្តាញ រៀបចំការជួបជុំអតីតនិស្សិតយ៉ាងងាយស្រួល',
    'landing.feature3Title': 'អន្តរកម្មពេលវេលាជាក់ស្តែង',
    'landing.feature3Desc': 'ផ្សព្វផ្សាយព័ត៌មាន មតិយោបល់ និងចូលចិត្ត ចែករំលែកសមិទ្ធផលអតីតនិស្សិតនិងចំណេះដឹងឧស្សាហកម្មគ្រប់ពេល',
    'landing.feature4Title': 'បណ្តាញសកល',
    'landing.feature4Desc': 'ភ្ជាប់អតីតនិស្សិតទូទាំងពិភពលោក ទម្លាយឧបសគ្គភូមិសាស្ត្រ បង្កើតបណ្តាញអន្តរជាតិ',
    'landing.feature5Title': 'ការអភិវឌ្ឍន៍ការងារ',
    'landing.feature5Desc': 'ចែករំលែកឱកាសការងារ ការណែនាំពីអ្នកជំនាញ គាំទ្រការរីកចម្រើនការងារអតីតនិស្សិត',
    'landing.feature6Title': 'ការការពារភាពឯកជន',
    'landing.feature6Desc': 'ការអ៊ិនគ្រីបសុវត្ថិភាពកម្រិតសហគ្រាស ការកំណត់ភាពឯកជនពេញលេញ ការពារព័ត៌មានផ្ទាល់ខ្លួន',
    'landing.dataSpeak': 'លេខនិយាយ',
    'landing.dataDesc': 'នៅពីក្រោយលេខនីមួយៗគឺជាទំនុកចិត្តនិងការគាំទ្ររបស់អតីតនិស្សិតរបស់យើង',
    'landing.stat1': 'អតីតនិស្សិតបានចុះឈ្មោះ',
    'landing.stat2': 'អ្នកប្រើប្រាស់សកម្ម',
    'landing.stat3': 'ព្រឹត្តិការណ៍បានរៀបចំ',
    'landing.stat4': 'កិច្ចសហការជោគជ័យ',
    'landing.testimonialTitle': 'សំឡេងអតីតនិស្សិត',
    'landing.testimonialSubtitle': 'ស្តាប់អ្វីដែលអតីតនិស្សិតរបស់យើងនិយាយ',
    'landing.testimonial1Name': 'ចាង មីង',
    'landing.testimonial1Title': 'ជំនាន់ 2015',
    'landing.testimonial1Company': 'អ្នកគ្រប់គ្រងផលិតផលជាន់ខ្ពស់នៅ Tencent',
    'landing.testimonial1Content': 'តាមរយៈបណ្តាញអតីតនិស្សិត ខ្ញុំបានរកឃើញឱកាសការងារបច្ចុប្បន្នរបស់ខ្ញុំ។ វេទិកានេះធ្វើឱ្យខ្ញុំភ្ជាប់ជាមួយអតីតនិស្សិតល្អៗ រៀននិងរីកចម្រើនជាមួយគ្នា។',
    'landing.testimonial2Name': 'លី ហួ',
    'landing.testimonial2Title': 'ជំនាន់ 2018',
    'landing.testimonial2Company': 'នាយកបច្ចេកទេសនៅ ByteDance',
    'landing.testimonial2Content': 'បណ្តាញអតីតនិស្សិតគឺជាកម្លាំងសំខាន់ក្នុងការអភិវឌ្ឍន៍អាជីពរបស់ខ្ញុំ។ ខ្ញុំមិនត្រឹមតែរកឃើញអ្នកណែនាំនៅទីនេះទេ ប៉ុន្តែក៏បានជួបមិត្តភក្តិដែលមានគំនិតដូចគ្នាជាច្រើន។',
    'landing.testimonial3Name': 'សារ៉ា ចេន',
    'landing.testimonial3Title': 'ជំនាន់ 2020',
    'landing.testimonial3Company': 'zaបេកប្រតិបត្តិក្រុមហ៊ុនចាប់ផ្តើម',
    'landing.testimonial3Content': 'ក្នុងនាមជាសហគ្រិន បណ្តាញអតីតនិស្សិតផ្តល់ឱ្យខ្ញុំនូវធនធាននិងការគាំទ្រដ៏មានតម្លៃ។ សូមអរគុណសម្រាប់ការធ្វើឱ្យទំនាក់ទំនងអតីតនិស្សិតកាន់តែជិតស្និទ្ធ!',
    'landing.ctaTitle': 'តើអ្នករួចរាល់ចាប់ផ្តើមដំណើរអតីតនិស្សិតរបស់អ្នកទេ?',
    'landing.ctaSubtitle': 'ចូលរួមជាមួយយើង ភ្ជាប់ជាមួយអតីតនិស្សិតល្អៗ រីកចម្រើនជាមួយគ្នា និងបង្កើតលទ្ធភាពបន្ថែមទៀត',
    'landing.ctaButton': 'ចុះឈ្មោះដោយឥតគិតថ្លៃ ចាប់ផ្តើមឥឡូវនេះ',
    'landing.footerTagline': 'ភ្ជាប់អតីតនិស្សិត · បង្កើតអនាគត',
    'landing.footerCopyright': '© 2024 Alumni Network. រក្សាសិទ្ធិគ្រប់យ៉ាង។',
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
